import type { Crop, CropNutrientDemand } from '@/types'

export const CROPS: Crop[] = [
  {
    id: 'crop-winterweizen',
    name_de: 'Winterweizen (E, A)',
    category: 'Getreide',
    sow_month_from: 10,
    sow_month_to: 11,
    harvest_month_from: 7,
    harvest_month_to: 8,
    ref_yield_dt_ha: 80,
    nmin_depth_cm: 90,
  },
  {
    id: 'crop-wintergerste',
    name_de: 'Wintergerste',
    category: 'Getreide',
    sow_month_from: 9,
    sow_month_to: 10,
    harvest_month_from: 7,
    harvest_month_to: 7,
    ref_yield_dt_ha: 70,
    nmin_depth_cm: 90,
  },
  {
    id: 'crop-winterraps',
    name_de: 'Winterraps',
    category: 'Ölfrüchte',
    sow_month_from: 8,
    sow_month_to: 9,
    harvest_month_from: 7,
    harvest_month_to: 8,
    ref_yield_dt_ha: 40,
    nmin_depth_cm: 90,
  },
  {
    id: 'crop-silomais',
    name_de: 'Silomais',
    category: 'Futterpflanzen',
    sow_month_from: 4,
    sow_month_to: 5,
    harvest_month_from: 9,
    harvest_month_to: 10,
    ref_yield_dt_ha: 450,
    nmin_depth_cm: 60,
  },
  {
    id: 'crop-zuckerrueben',
    name_de: 'Zuckerrüben',
    category: 'Hackfrüchte',
    sow_month_from: 3,
    sow_month_to: 4,
    harvest_month_from: 9,
    harvest_month_to: 11,
    ref_yield_dt_ha: 650,
    nmin_depth_cm: 90,
  },
]

export const CROP_NUTRIENT_DEMANDS: CropNutrientDemand[] = [
  // --- Winterweizen (E, A) --- ref_yield: 80 dt/ha
  {
    id: 'cnd-winterweizen-n',
    crop_id: 'crop-winterweizen',
    nutrient_type_id: 'nt-n',
    demand_kg_ha: 230,
    ref_yield_dt_ha: 80,
    per_yield_correction: 1.0,
    source: 'lfl',
    user_id: null,
    valid_from: '2025-01-01',
  },
  {
    id: 'cnd-winterweizen-p2o5',
    crop_id: 'crop-winterweizen',
    nutrient_type_id: 'nt-p2o5',
    demand_kg_ha: 64,
    ref_yield_dt_ha: 80,
    per_yield_correction: 0.80,
    source: 'lfl',
    user_id: null,
    valid_from: '2025-01-01',
  },
  {
    id: 'cnd-winterweizen-k2o',
    crop_id: 'crop-winterweizen',
    nutrient_type_id: 'nt-k2o',
    demand_kg_ha: 44,
    ref_yield_dt_ha: 80,
    per_yield_correction: 0.55,
    source: 'lfl',
    user_id: null,
    valid_from: '2025-01-01',
  },
  {
    id: 'cnd-winterweizen-mgo',
    crop_id: 'crop-winterweizen',
    nutrient_type_id: 'nt-mgo',
    demand_kg_ha: 16,
    ref_yield_dt_ha: 80,
    per_yield_correction: 0.20,
    source: 'lfl',
    user_id: null,
    valid_from: '2025-01-01',
  },
  {
    id: 'cnd-winterweizen-s',
    crop_id: 'crop-winterweizen',
    nutrient_type_id: 'nt-s',
    demand_kg_ha: 9.6,
    ref_yield_dt_ha: 80,
    per_yield_correction: 0.12,
    source: 'lfl',
    user_id: null,
    valid_from: '2025-01-01',
  },

  // --- Wintergerste --- ref_yield: 70 dt/ha
  {
    id: 'cnd-wintergerste-n',
    crop_id: 'crop-wintergerste',
    nutrient_type_id: 'nt-n',
    demand_kg_ha: 180,
    ref_yield_dt_ha: 70,
    per_yield_correction: 1.0,
    source: 'lfl',
    user_id: null,
    valid_from: '2025-01-01',
  },
  {
    id: 'cnd-wintergerste-p2o5',
    crop_id: 'crop-wintergerste',
    nutrient_type_id: 'nt-p2o5',
    demand_kg_ha: 56,
    ref_yield_dt_ha: 70,
    per_yield_correction: 0.80,
    source: 'lfl',
    user_id: null,
    valid_from: '2025-01-01',
  },
  {
    id: 'cnd-wintergerste-k2o',
    crop_id: 'crop-wintergerste',
    nutrient_type_id: 'nt-k2o',
    demand_kg_ha: 42,
    ref_yield_dt_ha: 70,
    per_yield_correction: 0.60,
    source: 'lfl',
    user_id: null,
    valid_from: '2025-01-01',
  },
  {
    id: 'cnd-wintergerste-mgo',
    crop_id: 'crop-wintergerste',
    nutrient_type_id: 'nt-mgo',
    demand_kg_ha: 14,
    ref_yield_dt_ha: 70,
    per_yield_correction: 0.20,
    source: 'lfl',
    user_id: null,
    valid_from: '2025-01-01',
  },
  {
    id: 'cnd-wintergerste-s',
    crop_id: 'crop-wintergerste',
    nutrient_type_id: 'nt-s',
    demand_kg_ha: 8.4,
    ref_yield_dt_ha: 70,
    per_yield_correction: 0.12,
    source: 'lfl',
    user_id: null,
    valid_from: '2025-01-01',
  },

  // --- Winterraps --- ref_yield: 40 dt/ha
  {
    id: 'cnd-winterraps-n',
    crop_id: 'crop-winterraps',
    nutrient_type_id: 'nt-n',
    demand_kg_ha: 200,
    ref_yield_dt_ha: 40,
    per_yield_correction: 1.5,
    source: 'lfl',
    user_id: null,
    valid_from: '2025-01-01',
  },
  {
    id: 'cnd-winterraps-p2o5',
    crop_id: 'crop-winterraps',
    nutrient_type_id: 'nt-p2o5',
    demand_kg_ha: 78,
    ref_yield_dt_ha: 40,
    per_yield_correction: 1.95,
    source: 'lfl',
    user_id: null,
    valid_from: '2025-01-01',
  },
  {
    id: 'cnd-winterraps-k2o',
    crop_id: 'crop-winterraps',
    nutrient_type_id: 'nt-k2o',
    demand_kg_ha: 24,
    ref_yield_dt_ha: 40,
    per_yield_correction: 0.60,
    source: 'lfl',
    user_id: null,
    valid_from: '2025-01-01',
  },
  {
    id: 'cnd-winterraps-mgo',
    crop_id: 'crop-winterraps',
    nutrient_type_id: 'nt-mgo',
    demand_kg_ha: 16.8,
    ref_yield_dt_ha: 40,
    per_yield_correction: 0.42,
    source: 'lfl',
    user_id: null,
    valid_from: '2025-01-01',
  },
  {
    id: 'cnd-winterraps-s',
    crop_id: 'crop-winterraps',
    nutrient_type_id: 'nt-s',
    demand_kg_ha: 18,
    ref_yield_dt_ha: 40,
    per_yield_correction: 0.45,
    source: 'lfl',
    user_id: null,
    valid_from: '2025-01-01',
  },

  // --- Silomais --- ref_yield: 450 dt/ha (Frischmasse)
  {
    id: 'cnd-silomais-n',
    crop_id: 'crop-silomais',
    nutrient_type_id: 'nt-n',
    demand_kg_ha: 200,
    ref_yield_dt_ha: 450,
    per_yield_correction: 0.09,
    source: 'lfl',
    user_id: null,
    valid_from: '2025-01-01',
  },
  {
    id: 'cnd-silomais-p2o5',
    crop_id: 'crop-silomais',
    nutrient_type_id: 'nt-p2o5',
    demand_kg_ha: 72,
    ref_yield_dt_ha: 450,
    per_yield_correction: 0.16,
    source: 'lfl',
    user_id: null,
    valid_from: '2025-01-01',
  },
  {
    id: 'cnd-silomais-k2o',
    crop_id: 'crop-silomais',
    nutrient_type_id: 'nt-k2o',
    demand_kg_ha: 216,
    ref_yield_dt_ha: 450,
    per_yield_correction: 0.48,
    source: 'lfl',
    user_id: null,
    valid_from: '2025-01-01',
  },
  {
    id: 'cnd-silomais-mgo',
    crop_id: 'crop-silomais',
    nutrient_type_id: 'nt-mgo',
    demand_kg_ha: 31.5,
    ref_yield_dt_ha: 450,
    per_yield_correction: 0.07,
    source: 'lfl',
    user_id: null,
    valid_from: '2025-01-01',
  },
  {
    id: 'cnd-silomais-s',
    crop_id: 'crop-silomais',
    nutrient_type_id: 'nt-s',
    demand_kg_ha: 13.5,
    ref_yield_dt_ha: 450,
    per_yield_correction: 0.03,
    source: 'lfl',
    user_id: null,
    valid_from: '2025-01-01',
  },

  // --- Zuckerrüben --- ref_yield: 650 dt/ha
  {
    id: 'cnd-zuckerrueben-n',
    crop_id: 'crop-zuckerrueben',
    nutrient_type_id: 'nt-n',
    demand_kg_ha: 170,
    ref_yield_dt_ha: 650,
    per_yield_correction: 0.02,
    source: 'lfl',
    user_id: null,
    valid_from: '2025-01-01',
  },
  {
    id: 'cnd-zuckerrueben-p2o5',
    crop_id: 'crop-zuckerrueben',
    nutrient_type_id: 'nt-p2o5',
    demand_kg_ha: 58.5,
    ref_yield_dt_ha: 650,
    per_yield_correction: 0.09,
    source: 'lfl',
    user_id: null,
    valid_from: '2025-01-01',
  },
  {
    id: 'cnd-zuckerrueben-k2o',
    crop_id: 'crop-zuckerrueben',
    nutrient_type_id: 'nt-k2o',
    demand_kg_ha: 195,
    ref_yield_dt_ha: 650,
    per_yield_correction: 0.30,
    source: 'lfl',
    user_id: null,
    valid_from: '2025-01-01',
  },
  {
    id: 'cnd-zuckerrueben-mgo',
    crop_id: 'crop-zuckerrueben',
    nutrient_type_id: 'nt-mgo',
    demand_kg_ha: 45.5,
    ref_yield_dt_ha: 650,
    per_yield_correction: 0.07,
    source: 'lfl',
    user_id: null,
    valid_from: '2025-01-01',
  },
  {
    id: 'cnd-zuckerrueben-s',
    crop_id: 'crop-zuckerrueben',
    nutrient_type_id: 'nt-s',
    demand_kg_ha: 13,
    ref_yield_dt_ha: 650,
    per_yield_correction: 0.02,
    source: 'lfl',
    user_id: null,
    valid_from: '2025-01-01',
  },
]

export function getCropById(id: string): Crop | undefined {
  return CROPS.find((c) => c.id === id)
}

export function getDemandsForCrop(cropId: string): CropNutrientDemand[] {
  return CROP_NUTRIENT_DEMANDS.filter((d) => d.crop_id === cropId)
}
