import type { FertilizerProduct } from '@/types'

export const FERTILIZER_PRODUCTS: FertilizerProduct[] = [
  {
    id: 'fp-kas',
    name: 'KAS 27% N',
    n_pct: 27,
    p2o5_pct: 0,
    k2o_pct: 0,
    mgo_pct: 4,
    s_pct: 0,
    form: 'mineral',
    affiliate_url: 'https://www.duenger-shop.de/kas-27',
    shop_name: 'Dünger-Shop.de',
    active: true,
  },
  {
    id: 'fp-harnstoff',
    name: 'Harnstoff 46% N',
    n_pct: 46,
    p2o5_pct: 0,
    k2o_pct: 0,
    mgo_pct: 0,
    s_pct: 0,
    form: 'mineral',
    affiliate_url: 'https://www.duenger-shop.de/harnstoff-46',
    shop_name: 'Dünger-Shop.de',
    active: true,
  },
  {
    id: 'fp-dap',
    name: 'DAP 18/46',
    n_pct: 18,
    p2o5_pct: 46,
    k2o_pct: 0,
    mgo_pct: 0,
    s_pct: 0,
    form: 'mineral',
    affiliate_url: 'https://www.duenger-shop.de/dap-18-46',
    shop_name: 'Dünger-Shop.de',
    active: true,
  },
  {
    id: 'fp-triplephosphat',
    name: 'Triple-Superphosphat 46% P2O5',
    n_pct: 0,
    p2o5_pct: 46,
    k2o_pct: 0,
    mgo_pct: 0,
    s_pct: 0,
    form: 'mineral',
    affiliate_url: 'https://www.duenger-shop.de/triple-superphosphat',
    shop_name: 'Dünger-Shop.de',
    active: true,
  },
  {
    id: 'fp-kornkali',
    name: 'Kornkali 40/6/4',
    n_pct: 0,
    p2o5_pct: 0,
    k2o_pct: 40,
    mgo_pct: 6,
    s_pct: 4,
    form: 'mineral',
    affiliate_url: 'https://www.duenger-shop.de/kornkali',
    shop_name: 'Dünger-Shop.de',
    active: true,
  },
  {
    id: 'fp-kali60',
    name: '60er Kali',
    n_pct: 0,
    p2o5_pct: 0,
    k2o_pct: 60,
    mgo_pct: 0,
    s_pct: 0,
    form: 'mineral',
    affiliate_url: 'https://www.duenger-shop.de/kali-60',
    shop_name: 'Dünger-Shop.de',
    active: true,
  },
  {
    id: 'fp-kieserit',
    name: 'Kieserit 25% MgO + 20% S',
    n_pct: 0,
    p2o5_pct: 0,
    k2o_pct: 0,
    mgo_pct: 25,
    s_pct: 20,
    form: 'mineral',
    affiliate_url: 'https://www.duenger-shop.de/kieserit',
    shop_name: 'Dünger-Shop.de',
    active: true,
  },
  {
    id: 'fp-npk-15-15-15',
    name: 'NPK 15-15-15',
    n_pct: 15,
    p2o5_pct: 15,
    k2o_pct: 15,
    mgo_pct: 0,
    s_pct: 0,
    form: 'mineral',
    affiliate_url: 'https://www.duenger-shop.de/npk-15-15-15',
    shop_name: 'Dünger-Shop.de',
    active: true,
  },
]
